#ifndef NETWORKED_INTERPOLATOR_HPP
#define NETWORKED_INTERPOLATOR_HPP

#include <functional>
#include <deque>
#include <optional>

#include "sbpt_generated_includes.hpp"

/**
 * @brief A network-aware interpolator
 *
 * This interpolator receives discrete state updates from a remote source (e.g., a game server)
 * at an *average* frequency R1, which can vary due to network latency and jitter. Locally, it
 * produces smooth interpolated states at a higher frequency R2 (e.g., render frame rate) while
 * maintaining a stable interpolation interval driven by a local clock.
 *
 * @note the term "interpolation window" is the active start/end state being used during interpolation
 *
 * @tparam StateToInterpolate The type of state being interpolated (e.g., GameUpdate, Transform, etc.).
 */
template <typename StateToInterpolate> class NetworkedInterpolator {
  public:
    struct InterpolationWindow {
        StateToInterpolate start;
        StateToInterpolate end;
        double t;

        // manual constructor because it doesn't get autogenerated by apple-clang13
        InterpolationWindow(const StateToInterpolate& s = {},
                            const StateToInterpolate& e = {},
                            double time = 0.0)
            : start(s), end(e), t(time) {}
    };

    using InterpolationFunc =
        std::function<StateToInterpolate(const StateToInterpolate &, const StateToInterpolate &, float)>;

    struct StartStateChangedSignal {
        StateToInterpolate state;
    };

    NetworkedPeriodicSignalQuantizer<StateToInterpolate> networked_periodic_signal_quantizer{3};

    bool logging_enabled = false;

    /// An optional function that can be passed that will augment the logging
    std::optional<std::function<std::string(const StateToInterpolate &)>> state_to_interpolate_to_string = std::nullopt;

    /**
     * @brief a signal that other non interpolated systems should bind to to synchronize with the interpolation
     *
     * Because interpolation imposes a delay on the rendering of the interpolated objects as we have to wait until we
     * have two states so that we can interpolate between them, then this means that if a system executed logic based on
     * states received from the server the moment that it was received, then there would be a synchronization issue
     * between this system and the interpolated state.
     *
     * Therefore in order for non-interpolated systems to say in sync with the interpolated state, we need to
     * synchronize them whenever the active start state changes, here's why that makes sense. Consider a sound system,
     * as mentioned above, if we just played sounds the moment they were received, then there would be an offset between
     * say a players interpolated position and the moment they make a sound when they jump, and the sound would occur
     * before you jump off the ground. Thus by playing the sound based on the active start state it allows the sound to
     * stay roughly in sync with the current interpolated state.
     *
     */
    SignalEmitter start_state_changed_synchronization;

    unsigned int num_extra_states_to_be_left_in_the_buffer;

    /**
     * @brief Construct a networked interpolator with a user-defined interpolation function and rate.
     *
     * @param interpolate_func Function defining how to interpolate between two states.
     * @param receive_frequency Frequency (Hz) representing the expected network tick rate.
     */
    NetworkedInterpolator(InterpolationFunc interpolate_func, float receive_frequency,
                          // keep these parameters at end.
                          bool logging_enabled = false,
                          std::optional<std::function<std::string(const StateToInterpolate &)>>
                              state_to_interpolate_to_string = std::nullopt)
        : interpolate_func(interpolate_func), first_interpolation_window_has_been_initialized(false),
          logging_enabled(logging_enabled), state_to_interpolate_to_string(state_to_interpolate_to_string) {
        networked_periodic_signal_quantizer.output_emitter.template connect<std::optional<StateToInterpolate>>(
            [&](const std::optional<StateToInterpolate> &new_state) {
                GlobalLogSection _("received new state to interpolate signal", logging_enabled);
                if (new_state.has_value()) {
                    global_logger->debug("had value");

                    // startfold initialized first interpolation window
                    if (active_start_state == std::nullopt) {
                        active_start_state = new_state;
                        global_logger->debug("just initialized first start state");
                        return;
                    } else if (active_end_state == std::nullopt) {
                        active_end_state = new_state;
                        global_logger->debug("just initialized first end state ");
                        first_interpolation_window_has_been_initialized = true;
                        global_logger->debug("interpolation window is initialized");
                        start_state_changed_synchronization.emit(StartStateChangedSignal{active_start_state.value()});
                        return;
                    }
                    // endfold

                    global_logger->debug("regular interpolation window change");
                    active_start_state = active_end_state;
                    active_end_state = new_state;
                    // we know this is anew state because we are in the new_state.has_value() case.
                    start_state_changed_synchronization.emit(StartStateChangedSignal{active_start_state.value()});
                } else {
                    global_logger->debug("no value");
                    global_logger->debug("setting active_start_state to end_start_state, this will lead to multiple "
                                         "frames where the entity is stuck in place");
                    // NOTE: this is a very important line, we only ever get here if we haven't registered a new state
                    // since last time this was called, this occurs when the network variance causes one of the packets
                    // to take longer than it regularly would. If we didn't add this line then the active start/end
                    // state so the interpolation window is the same as the last interpolation window which would look
                    // strange because it would look like you interpolate from point a to point b, and then do that
                    // again, this line fixes that because it makes a "constant interpolation window" as the start and
                    // end state become the same, once this is true all interpolation attempts always just yield
                    // active_end_state which is the most up to date state, which is better than doing the same
                    // interpolation again.
                    active_start_state = active_end_state;
                }

                log_active_interpolation_window();
            });
    }

    void log_active_interpolation_window() {
        if (state_to_interpolate_to_string and active_start_state and active_end_state) {
            GlobalLogSection _("active interpolation window");
            global_logger->debug("START: {}", (*state_to_interpolate_to_string)(active_start_state.value()));
            global_logger->debug("END: {}", (*state_to_interpolate_to_string)(active_end_state.value()));
            global_logger->debug("t: {}", active_t);
        } else {
            global_logger->debug("interpolating between start and end with t : {}", active_t);
        }
    }

    /**
     * @brief Register a new incoming network state.
     *
     * This adds the state to a buffer for future use. It does *not* immediately change
     * the currently active interpolation window. The window is updated only at the local
     * receive signal rate inside update_interpolated_state().
     */
    void register_new_state(const StateToInterpolate &new_state) {
        networked_periodic_signal_quantizer.push(new_state);
    }

    std::optional<InterpolationWindow> get_interpolation_window() {
        auto opt_start = get_active_start_state();
        auto opt_end = get_active_end_state();
        auto t = get_active_t();

        if (opt_start.has_value() and opt_end.has_value()) {
            return InterpolationWindow(opt_start.value(), opt_end.value(), t);
        }
        return std::nullopt;
    }

    /**
     * @brief Update the interpolated state based on local interpolation progress.
     *
     * Should be called at the render or update frequency R2 (e.g., once per frame).
     *
     * Behavior:
     * - If not initialized and enough buffered states exist, initializes the active window.
     * - Interpolates between the active start and end states using the cycle progress.
     * - When the local receive signal fires:
     *     * If a buffered network state exists, consume it as the new active_end_state.
     *     * Otherwise, copy active_end_state to active_start_state to hold the last known state.
     */
    void update() {
        GlobalLogSection _("networked interpolator update", logging_enabled);

        // TODO: do we need a function called get progress at the last periodic signal processing? I think if I want to
        // be super safe, because later down this function we will get the progress and in that time it could have
        // rolled over... If interpolation seems to flicker then this might be the culprit
        networked_periodic_signal_quantizer.update();

        if (not first_interpolation_window_has_been_initialized) {
            global_logger->debug("interpolation window not initialized not running anything");
            return;
        }

        active_t = networked_periodic_signal_quantizer.output_signal
                       .cycle_progress_at_last_process_and_get_signal_call; // [0,1] through current local interval

        log_active_interpolation_window();

        // .value() usage is validated by the fact that the interpolation window has been initialized
        current_interpolated_state = interpolate_func(active_start_state.value(), active_end_state.value(), active_t);

        if (state_to_interpolate_to_string) {
            global_logger->debug("the interpolated state is: {}",
                                 (*state_to_interpolate_to_string)(current_interpolated_state.value()));
        }
    }

    /// @brief Get the current interpolated state.
    const std::optional<StateToInterpolate> &get_state() const { return current_interpolated_state; }

    /// @brief Get the currently active "start" state being interpolated from.
    const std::optional<StateToInterpolate> &get_active_start_state() const { return active_start_state; }

    const double &get_active_t() const { return active_t; }

    /// @brief Get the currently active "end" state being interpolated toward.
    const std::optional<StateToInterpolate> &get_active_end_state() const { return active_end_state; }

  private:
    /**
     * @brief The currently active start state (previous state in interpolation).
     *
     * Optional is used as this class is un-initialized before any states are registered, and allows us to safely access
     * this member, once the first call to update is when there is at least two elements then this is forever a real
     * value
     */
    std::optional<StateToInterpolate> active_start_state = std::nullopt;

    /// @brief The currently active t value (which is how far we are between the two states in time, normalized [0, 1])
    double active_t = 0;

    /**
     * @brief The currently active end state (next target state in interpolation).
     *
     * Optional is used as this class is un-initialized before any states are registered, and allows us to safely access
     * this member, once the first call to update is when there is at least two elements then this is forever a real
     * value
     */
    std::optional<StateToInterpolate> active_end_state = std::nullopt;

    /**
     * @brief The most recent interpolated result.
     *
     * Optional is used as this class is un-initialized before any states are registered, and allows us to safely access
     * this member, once the first call to update is when there is at least two elements then this is forever a real
     * value
     */
    std::optional<StateToInterpolate> current_interpolated_state = std::nullopt;

    /// @brief Whether the interpolation window is initialized. Only ever false at the start
    bool first_interpolation_window_has_been_initialized = false;

    InterpolationFunc interpolate_func;
};

#endif // NETWORKED_INTERPOLATOR_HPP
